[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
wibe_casino = "BfdTrxqFfFhe4xA3XniqVWzVkQKX88za5yuA4FRq3ktw"

[programs.localnet]
wibe_casino = "BfdTrxqFfFhe4xA3XniqVWzVkQKX88za5yuA4FRq3ktw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000

[test.validator]
url = "https://api.devnet.solana.com"
